// Autogenerated file, do not manually modify

export enum Language {
    /**
     * Default language of the Office Application or English if not available.
     */
    Default = "Default",

    English = "English",
    Japanese = "Japanese",
    Spanish = "Spanish",
    French = "French",
    German = "German",
    Chinese = "Chinese",

    /**
     * Pseudo language for testing.
     */
    Pseudo = "Pseudo",
}
