// Autogenerated file, do not manually modify

import { Language } from "./Language";

/**
 * Map of display languages to Language enum values.
 * Only do prefix matching for the language code.
 * https://www.rfc-editor.org/info/bcp47
 */
export const languageMap = new Map<string, Exclude<Language, Language.Default>>([
    ["en", Language.English],
    ["ja", Language.Japanese],
    ["es", Language.Spanish],
    ["fr", Language.French],
    ["de", Language.German],
    ["zh", Language.Chinese],
]);
